// <auto-generated />
using BulkyWeb.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BulkyWeb.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.7.23375.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BulkWeb.Models.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "shiv khera",
                            Description = "Complete CPP programming",
                            ISBN = "shiv khera",
                            ListPrice = 100.0,
                            Price = 500.0,
                            Price100 = 1500.0,
                            Price50 = 1000.0,
                            Title = "CPP"
                        },
                        new
                        {
                            Id = 2,
                            Author = "shiv khera",
                            Description = "Complete JAVA programming",
                            ISBN = "shiv khera",
                            ListPrice = 200.0,
                            Price = 600.0,
                            Price100 = 1700.0,
                            Price50 = 1100.0,
                            Title = "JAVA"
                        },
                        new
                        {
                            Id = 3,
                            Author = "shiv khera",
                            Description = "Complete C# programming",
                            ISBN = "shiv khera",
                            ListPrice = 250.0,
                            Price = 650.0,
                            Price100 = 1750.0,
                            Price50 = 1150.0,
                            Title = "C#"
                        },
                        new
                        {
                            Id = 4,
                            Author = "shiv khera",
                            Description = "Complete DOT NET programming",
                            ISBN = "shiv khera",
                            ListPrice = 350.0,
                            Price = 750.0,
                            Price100 = 1850.0,
                            Price50 = 1250.0,
                            Title = "DOT NET"
                        },
                        new
                        {
                            Id = 5,
                            Author = "shiv khera",
                            Description = "Complete C# programming",
                            ISBN = "shiv khera",
                            ListPrice = 350.0,
                            Price = 750.0,
                            Price100 = 1950.0,
                            Price50 = 1250.0,
                            Title = "C#"
                        });
                });

            modelBuilder.Entity("BulkyWeb.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "SciFi"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "History"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "test1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
